# @package _global_

defaults:
  - _self_
  - data: cifar.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: cifar.yaml
  - logger: null
  - trainer: default.yaml
  - paths: default.yaml
  - hydra: default.yaml

task_name: "eval"

tags: ["dev"]
ckpt_path:  /Users/mdhakad/Desktop/emlo4-lightning/outputs/checkpoints/model.ckpt