# @package _global_

defaults:
  - _self_
  - data: cifar.yaml # choose datamodule with `test_dataloader()` for evaluation
  - model: cifar.yaml
  - trainer: default.yaml
  - paths: default.yaml


  - experiment: null

task_name: "infer"

tags: ["dev"]
ckpt_path:  ${paths.root_dir}/outputs/2023-07-03/22-28-39/lightning_logs/version_0/checkpoints/epoch=0-step=313.ckpt

infer_image_path: ${paths.root_dir}/data/PetImages_split/infer/Cat/12.jpg